name: p2p_call_sample
description: P2P Calls Sample

version: 1.4.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectycube_sdk: ^2.1.1
#  connectycube_sdk:
#    path: ../../flutter-sdk
  shared_preferences: ^2.0.6
  connectycube_flutter_call_kit: ^2.0.3
#  connectycube_flutter_call_kit:
#    path: ../../connectycube-flutter-call-kit/connectycube_flutter_call_kit
  platform_device_id: ^1.0.1
  universal_io: ^2.0.4
  web_browser_detect: ^2.0.2
  flutter_background: ^1.1.0
  permission_handler: ^9.2.0
  device_info_plus: ^3.2.3
  video_player: ^2.2.3
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1
  location: ^4.4.0
  geocoding: ^2.0.5
  another_flushbar: ^1.10.29
  tflite_flutter: ^0.9.0
  camera: ^0.10.0
  path_provider: ^2.0.9
  path: ^1.8.0
  google_ml_kit: ^0.5.0
  image: ^3.0.2
  font_awesome_flutter: ^9.0.0
  get_it: ^7.2.0
  file_picker: ^4.2.2+1
  syncfusion_flutter_pdfviewer: ^19.1.69-beta
  native_device_orientation: ^1.0.0
  wakelock: ^0.6.2
  auto_orientation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/launcher/launcher_icon.png"
  image_path_android: "assets/launcher/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - icon-app.png
    - splash-screen.png
    - logo_smartschool.png
    - logo_disdik_sulsel.png
    - scanner.png
    - classroom.png
    - location.png
    - office.png
    - izin.png
    - absen.png
    - info.png
    - timecheck.png
    - timex.png
    - mobilefacenet.tflite